# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LastApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift'

  # Pods for LastApp

  target 'LastAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
